x-hadoop_environment: &hadoop_environment
  CORE-SITE.XML_fs.default.name: hdfs://namenode
  CORE-SITE.XML_fs.defaultFS: hdfs://namenode
  HDFS-SITE.XML_dfs.namenode.rpc-address: namenode:8020
  HDFS-SITE.XML_dfs.replication: "1"

services:
  hive:
    image: apache/hive:3.1.3
    hostname: hive
    ports:
      - 10000:10000
      - 10002:10002
    environment:
      <<: *hadoop_environment
      HIVE_VERSION: 3.1.3
      SERVICE_NAME: hiveserver2

  namenode:
    image: apache/hadoop:3
    hostname: namenode
    command: ["hdfs", "namenode"]
    ports:
      - 9870:9870
    environment:
      <<: *hadoop_environment
      ENSURE_NAMENODE_DIR: "/tmp/hadoop-hadoop/dfs/name"

  datanode:
    image: apache/hadoop:3
    hostname: datanode
    command: ["hdfs", "datanode"]
    environment: *hadoop_environment
